export const data = [
  [
    {
      date: "1901",
      h3: "Kelahiran Soekarno",
      h4: "6 Juni",
      p: " Sukarno terlahir dengan nama Kusno pada 6 Juni 1901 di Surabaya dari seorang ibu keturunan bangsawan Bali bernama Ida Ayu Nyoman Rai dan ayahnya adalah keturunan Sultan Kediri bernama Raden Sukemi Sosrodiharjo.",
    },
    {
      date: "1911",
      h3: "Soekarno ketika SD",
      h4: "~",
      p: "Soekarno pindah ke ELS ( Eerste Inlandse School ) yang setara dengan Sekolah Dasar (SD) yang khusus dipersiapkan untuk masuk Hogere Burger School (HBS) di Surabaya.",
    },
    {
      date: "1915",
      h3: "Soekarno Muda",
      h4: "~",
      p: "Tahun 1915 Soekarno pun menamatkan sekolahnya di ELS dan kemudian tinggal di rumah sahabat ayahnya, Haji Oemar Said Tjokroaminoto atau HOS Cokroaminoto. Di Kediaman Cokroaminoto, Soekarno mulai kenal dan berinteraksi dengan tokoh-tokoh hebat, seperti Dr. Douwes Dekker, Tjipto Mangunkusumo, dan Ki Hajar Dewantara. Merekalah pemimpin organisasi National Indische Partij saat itu. ",
    },
    {
      date: "1921",
      h3: "Lulus Dari HBS",
      h4: "~",
      p: "Bersekolah di HBS memberi banyak pengalaman dan pelajaran bagi Soekarno, hingga akhirnya lulus di tahun 1921. Setelah itu Soekarno pun kembali pindah tempat tinggal, yakni ke Bandung dan tinggal bersama Haji Sanusi untuk melanjutkan pendidikannya di Technische Hooge School (THS) jurusan teknik sipil.",
    },
    {
      date: "1926",
      h3: "Cikal Bakal Berdirinya Partai Besar",
      h4: "~",
      p: "Soekarno kemudian mendirikan Algemeene Studie (ASC) di Bandung pada tahun 1926 yang merupakan hasil inspirasi dari Dr. Soetomo di Indonesische Studie Club. Organisasi ASC inilah yang menjadi cikal bakal berdirinya partai besar di Indonesia.",
    },
    {
      date: "1929",
      h3: "Ditangkapnya Soekarno",
      h4: "29 Desember",
      p: "Soekarno ditangkap di Yogyakarta untuk dipindahkan ke penjara Banceuy di Bandung. Kemudian pada tahun 1930 dipindahkan ke penjara Sukamiskin dan di tahun ini pula Soekarno mengeluarkan pledoi Indonesia Menggugat yang sangat fenomenal saat itu sampai akhirnya dibebaskan pada 31 Desember 1931. ",
    },
    {
      date: "1931",
      h3: "Soekarno Kembali Ditangkap",
      h4: "31 Desember",
      p: "Namun keaktifannya di Partindo kembali mengantarkan ke penjara pada tahun 1933 di pengasingan Folders karena pergerakan yang bahaya bagi Belanda. Karena pengasingannya yang cukup lama dan sangat jauh hampir membuat tokoh-tokoh nasional Indonesia yang lainnya melupakan keberadaan dan keterlibatan Soekarno. Hal itu tidak membuatnya menyerah dan Soekarno terus mengirim surat kepada Ahmad Hasan, seorang Guru Persatuan Islam. ",
    },
    {
      date: "1938-1942",
      h3: "Soekarno Diasingkan",
      h4: "~",
      p: "Tahun 1938 Soekarno kemudian diasingkan ke Provinsi Bengkulu sampai tahun 1942. Pada masa penjajahan Jepang tahun 1942 Soekarno baru kembali dibebaskan. ",
    },
    {
      date: "1943",
      h3: "Soekarno Diberikan Bintang Kekaisaran",
      h4: "~",
      p: "Setelah melalui perjalanan panjang, tahun 1943 perdana menteri Jepang, Hideki Tojo mengundang Soekarno, Muhammad Hatta, dan Ki Bagoes Hadikoesoemo yang kemudian disambut hangat kehadirannya oleh Kaisar Hirohito. Mereka bertiga telah dianggap sebagai keluarga kaisar Jepang dengan diberikannya Bintang Kekaisaran (Ratna Suci).",
    },
    {
      date: "~",
      h3: "Bangkitnya Semangat Perjuangan",
      h4: "~",
      p: "Sejak masa penjajahan Jepang itulah banyak muncul organisasi, seperti Jawa Hokokai, BPUPKI, Pusat Tenaga Rakyat (Putera) hingga PPKI dengan tokoh-tokoh utama yakni Soekarno, K.H Mas Mansyur, Ki. Hajar Dewantara, dan tokoh lainnya yang aktif di organisasi pergerakan nasional. Akhirnya tokoh-tokoh pergerakan nasional tersebut melakukan buy clenbuterol bekerjasama dengan pemerintah jepang untuk kemerdekaan Indonesia. Meskipun tetap ada yang melakukan gerakan bawah tanah seperti Amir Sjarifuddin dan Sutan Syahrir yang tidak sepenuhnya percaya pada Jepang dan menganggapnya berbahaya dan fasis. ",
    },
    {
      date: "1945",
      h3: "Kemerdekaan Indonesia",
      h4: "17 Agustus",
      p: "Selama perjuangan yang panjang akhirnya Soekarno dan Moh. Hatta memproklamasikan kemerdekaan RI pada 17 Agustus 1945 yang didesak oleh kaum muda dan sempat diculik ke Rengasdengklok. Sejak itulah Soekarno diangkat menjadi Presiden pertama Indonesia dan mulai dikenal sebagai Sang Proklamator yang didampingi Mohammad Hatta sebagai wakilnya. Sebelumnya pada 1 Juni 1945 dalam sidang BPUPKI Soekarno sudah mengemukakan gagasan tentang dasar Negara, yakni Pancasila yang sekarang masih menjadi dasar Negara kita. ",
    },
  ],
  [
    {
      date: "1902",
      h3: "Kelahiran Mohammad Hatta",
      h4: "12 Agustus",
      p: "Mohammad Hatta lahir di Bukittinggi, Sumatera Barat, 12 Agustus 1902. Ia merupakan anak kedua dari pasangan Muhammad Djamil dan Siti Saleha yang asli dari Minangkabau. Sang ayah meninggal dunia saat usianya 7 bulan. Kemudian, ibunya menikah lagi dengan Agus Haji Ning, seorang pedagang asal Palembang. Pernikahan mereka dikaruniai 4 orang anak perempuan.",
    },
    {
      date: "1919",
      h3: "Pendidikan Hatta",
      h4: "~",
      p: "Pria yang akrab disapa Bung Hatta ini pun mengenyam pendidikan pertama kali di Sekolah Dasar Melayu Fort de kock. Namun, kemudian pindah ke Europeesche Lagere School (ELS), Padang (Kini SMA Negeri 1 Padang) dan melanjutkan ke Meer Uirgebreid Lagere School (MULO), Padang hingga tahun 1919. Sedangkan, sekolah tingginya sendiri ia lanjutkan ke Sekolah Tinggi Dagang Prins Hendrik School, Batavia. ",
    },
    {
      date: "1921",
      h3: "Hatta Mengenyam Pendidikan di Belanda",
      h4: "~",
      p: "Pada tahun 1921, Hatta hijrah ke Belanda untuk melanjutkan studinya di Handels Hogeschool (sekarang namanya Universitas Erasmus Rotterdam). Ia bergabung dengan perkumpulan pelajar tanah air, Indische Vereeniging",
    },
    {
      date: "1922",
      h3: "Perhimpunan Indonesia",
      h4: "~",
      p: "Pada tahun 1922, Hatta kembali menduduki posisi bendahara di Perhimpunan Indonesia dan 3 tahun kemudian ia terpilih sebagai ketua. Hatta juga sempat mengatur majalah Hindia Putera yang berganti nama menjadi Indonesia Merdeka di tahun 1924.",
    },
    {
      date: "1923",
      h3: "Liga Menentang Imperialisme dan Kolonialisme di Belanda",
      h4: "~",
      p: "Setahun kemudian, Hatta bergabung dengan Liga Menentang Imperialisme dan Kolonialisme di Belanda. Di sanalah ia bertemu dengan Jawaharhal Nehru, aktivis nasionalis asal India. Keaktifannya di beberapa organisasi tersebut membuat studinya molor hingga tahun 1932.",
    },
    {
      date: "1932",
      h3: "Hatta Kembali ke Tanah Air",
      h4: "~",
      p: "Setelah kembali ke tanah air pada tahun 1932, Hatta bergabung dengan Club Pendidikan Nasional Indonesia yang bertujuan untuk membuka mata masyarakat Indonesia tentang dunia politik dengan mengadakan berbagai pelatihan.",
    },
    {
      date: "1937",
      h3: "Hatta Dipindahkan ke Maluku",
      h4: "~",
      p: "Pada tahun 1937, Hatta dan Syahrir dipindahkan ke Banda Neira, Maluku. Sewaktu di Banda Neira, Ia bercocok tanam dan menulis di surat kabar Sin Tit Po dan Nationale Commantaren. ",
    },
    {
      date: "1942",
      h3: "Hatta Dipindahkan ke Sukabumi",
      h4: "~",
      p: "Pada tahun 1942, pria bedarah Minang ini pun dipindahkan ke Sukabumi, selang sebulan kemudian Belanda menyerah kepada Jepang. Baru setelah itu, ia dibawa ke Jakarta. Di Jakarta, Hatta bertemu dengan Mayor Jenderal Harada yang menawarkan kerja sama dengannya. Jika Hatta mau, Ia akan mendapat posisi penting. Namun, Hatta menolak dan memilih jadi penasehat dan berkantor di Pegangsaan Timur.",
    },
    {
      date: "1945",
      h3: "BPUPKI berganti nama",
      h4: "Awal Agustus",
      p: "BPUPKI (Badan Penyelidik Usaha-usaha Persiapan Kemerdekaan Indonesia) berganti nama menjad PPKI (Panitia Persiapan Kemerdekaan Indonesia) dengan Soekarno sebagai ketua dan Hatta sebagai wakilnya. Pelantikan tersebut dilaksanakan di Dalat Vietnam. ",
    },
    {
      date: "1945",
      h3: "Peristiwa Rengasdengklok",
      h4: "16 Agustus",
      p: "Terjadi perbedaan pendapat antara golongan tua dan golongan muda sehingga terjadilah peristiwa Rengasdengklok pada tanggal 16 Agustus 1945, Soekarno dan Hatta dibawa ke Rengasdengklok oleh para pemuda PETA di antaranya Soekarni, Wikana dan Chaerul Saleh untuk dibujuk segera memproklamasikan kemerdekaan karena saat itu sedang terjadi kevakuman pemerintah akibat Hiroshima-Nagasaki dibom oleh sekutu.",
    },
    {
      date: "1945",
      h3: "Kemerdekaan Indonesia",
      h4: "17 Agustus",
      p: "Tepat tanggal 17 Agustus 1945, pukul 10.00, Soekarno dan Hatta membacakan teks proklamasi di kediaman Soekarno. Pada awalnya pembacaan teks proklamasi akan dilaksanakan di Lapangan IKADA (sekarang Monas). Namun, karena sudah tersiar kabar di tempat itu akan ada acara keesokan harinya, maka sudah ada tentara-tentara Jepang berjaga-jaga. Akhirnya, teks proklamasi dibacakan di kediaman Soeakrno. ",
    },
  ],
  [
    {
      date: "1921",
      h3: "Kelahiran Soeharto",
      h4: "8 Juni",
      p: "Soeharto merupakan seseorang yang lahir di Yogyakarta, lebih tepatnya di desa Kemusuk, Argomulyo. Ketika lahir, Soeharto bisa dikatakan sebagai keluarga yang kurang mampu. Soeharto adalah seorang anak yang lahir dari ayah yang bernama Kertosudiro dan ibu yang bernama Sukirah. Ayah Soeharto merupakan seorang petani di desanya.",
    },
    {
      date: "1929",
      h3: "Pendidikan Soeharto",
      h4: "~",
      p: "Saat berusia delapan tahun, Soeharto baru masuk sekolah dasar, tetapi ia beberapa pindah sekolah. Pada awal masuk sekolah, Soeharto bersekolah di Sekolah Dasar (SD) Puluhan, Godean. Namun, ketika ibu dan ayah tirinya pindah rumah ke Kemusuk Kidul maka Soeharto juga pindah sekolah ke Sekolah Dasar (SD) Pedes. Kemudian Soeharto melanjutkan Sekolah Menengah Pertama (SMP) Muhammadiyah di Yogyakarta. Setelah tamat dari SMP, Soeharto ingin sekali melanjutkan pendidikannya ke jenjang Sekolah Menengah Atas (SMA). Namun, karena keadaan ekonomi keluarga dan keterbatasan biaya yang dimiliki oleh orang tuanya membuat Soeharto harus mengurungkan niatnya itu. ",
    },
    {
      date: "1947",
      h3: "Pernikahan Soeharto",
      h4: "26 Desember",
      p: "Saat berusia 26 tahun, Soeharto menikahi Siti Hartinah yang berusia 24 tahun. Istri Soeharto merupakan putri dari Soemoharjomo, wedana di Wuryantoro. Soemoharjomo juga merupakan seorang pegawai Keraton Mangkunegaran, Surakarta. Pernikahan Soeharto dan Siti Hartinah terlaksana pada tanggal 26 Desember tahun 1947 dan dilaksanakan di Solo. ",
    },
    {
      date: "1945",
      h3: "Soeharto Menjadi TNI",
      h4: "5 Oktober",
      p: "Sebelum memulai karir politiknya, Soeharto menjadi anggota dari lembaga ketentaraan yaitu TNI (Tentara Nasional Indonesia). Soeharto diangkat menjadi anggota TNI pada tanggal 5 Oktober 1945.",
    },
    {
      date: "1949",
      h3: "Soeharto Makin Dikenal Oleh Masyarakat",
      h4: "1 Maret",
      p: "Nama Soeharto semakin dikenal oleh banyak orang karena ia berperan penting dalam serangan untuk menguasai kota Yogyakarta. Kesuksesannya dalam menguasai Yogyakarta tidak bisa lepas dari peran dan perjuangan masyarakat Indonesia dalam melawan pihak Belanda.",
    },
    {
      date: "1961",
      h3: "Soeharto Memimpin Komando Mandala",
      h4: "~",
      p: "Soeharto berhasil menjadi seorang tentara dengan pangkat Brigadir Jenderal dan memimpin Komando Mandala yang bertugas untuk merebut kembali Irian Barat. Komando Mandala dilaksanakan pada tahun 1961, dan dari Komando Mandala ini Soeharto mendapatkan pengalaman yang sangat berharga yaitu ia bisa berkenalan dengan orang-orang yang memiliki peran penting dan strategis.",
    },
    {
      date: "1962",
      h3: "Soeharto Naik Pangkat",
      h4: "~",
      p: "Soeharto mendapatkan kenaikan pangkat setelah selesai menjalankan tugas di Irian Barat dan kembali dari Indonesia Timur. Pangkat yang diperoleh Soeharto adalah Mayor Jenderal dan oleh Jenderal A.H. Nasution, ia ditarik ke markas besar ABRI (Angkatan Bersenjata Republik Indonesia). Bukan hanya itu, pada tahun 1962, Soeharto mendapatkan kenaikan menjadi Panglima Komando Cadangan Strategis Angkatan Darat (Kostrad).",
    },
    {
      date: "1965",
      h3: "Gerakan 30 September",
      h4: "1 Oktober",
      p: "Pada dini hari 1 Oktober 1965, terjadi penculikan dan pembunuhan terhadap enam orang Jenderal. Kelompok yang menculik dan membunuh enam Jenderal itu mengaku sebagai kelompok Gerakan 30 September (G30S). Semua kejadian itu terjadi begitu cepat hingga muncul Surat Perintah 11 Maret (Supersemar) dari Presiden Soekarno yang berisi tentang pemberian kewenangan dan mandat kepada Soeharto",
    },
    {
      date: "1966",
      h3: "Supersemar",
      h4: "11 Maret",
      p: "Sejak dikeluarkannya Surat Perintah 11 Maret (Supersemar) oleh Soekarno, jabatan Panglima Komando Panglima Komando Pemulihan Keamanan dan Ketertiban (Kopkamtib) dipegang oleh Soeharto.",
    },
    {
      date: "1968",
      h3: "Soeharto Dilantik Menjadi Presiden",
      h4: "27 Maret",
      p: "Pada tanggal 27 Maret 1968, Soeharto dilantik oleh MPRS untuk menjadi Presiden Republik Indonesia. Dengan pelantikan ini maka menjadi tanda lahirnya masa pemerintahan Orde Baru. Sebenarnya Soeharto mulai menjabat sebagai Presiden Republik Indonesia sejak tahun 1966, tetapi baru dilantik oleh MPRS pada tahun 1968. Dengan kata lain, Soeharto baru sah menjadi Presiden Republik Indonesia yang kedua di tahun 1968.",
    },
  ],
  [
    {
      date: "1936",
      h3: "Kelahiran BJ Habibie",
      h4: "25 Juni",
      p: "Masa kecil Bacharuddin Jusuf Habibie berada di Pare-pare Sulawesi Selatan bersama ayah ibu dan tujuh saudaranya. Alwi Abdul Jalil Habibie adalah ayah BJ Habibie yang merupakan seorang ahli pertanian asal Gorontalo dan Sang ibu bernama R.A Tuti Marini Puspowardojo yang merupakan spesialis mata asal Yogyakarta.BJ Habibie ditinggalkan sang Ayah meninggal dunia saat usianya masih sangat muda, yakni 14 tahun.",
    },
    {
      date: "1955",
      h3: "Pendidikan BJ Habibie",
      h4: "~",
      p: "SMAK Dago Bandung adalah sekolah tempat BJ Habibie mengenyam pendidikan sampai kemudian melanjutkan ke perguruan tinggi di ITB. BJ Habibie hanya kuliah selama setahun di ITB kemudian melanjutkan studinya di RWTH Aachen, Jerman selama 10 tahun.",
    },
    {
      date: "1960",
      h3: "BJ Habibie Menyelesaikan Studinya",
      h4: "~",
      p: "Tahun 1960 BJ Habibie berhasil menyelesaikan studinya untuk gelar Diploma Ing-nya di Technische Hochschule dengan predikat sempurna atau Cum Laude yang rata-rata nilainya adalah 9,5. Gelar Insinyur inilah yang membuatnya bisa bekerja di Firma Talbot, Industri Kereta Api di Jerman. ",
    },
    {
      date: "1965",
      h3: "BJ Habibie Mengambil Gelar Doktor",
      h4: "~",
      p: "Tak puas bergelar Diploma Ing, Habibie kemudian melanjutkan studinya untuk gelar Doktor di Technischule Die Facultaet Fuer Maschinenwesen Aachean. Di tempat tersebut ia mendapat gelar Dr. Ingenieur atau Dr. Ing dengan predikat Summa Cumlaude pada tahun 1965.",
    },
    {
      date: "1973",
      h3: "Soeharto Mengutus Orang Untuk Menemui Habibie",
      h4: "~",
      p: "Pada tahun 1973 Soeharto mengutus Ibnu Sutowo untuk pergi ke Jerman dan menemui BJ Habibie aga ia berkarir di tanah air. Maka setahun dari kedatangan Ibnu Sutowo, BJ Habibie pun pulang ke Indonesia dan memulai karirnya di Lembaga Industri Pesawat Terbang Nurtanio (LIPNUR) sebagai pemimpin.",
    },
    {
      date: "1974",
      h3: "Karir Politik BJ Habibie",
      h4: "~",
      p: "Karir politik BJ Habibie dimulai sejak ia kembali ke Indonesia pada tahun 1974 atas perintah Soeharto. Mulai 1978 BJ Habibie ditetapkan sebagai Menteri Riset dan Teknologi 10 dekade hingga Maret 1998 di masa pemerintahan presiden Soeharto. Selain itu ia juga sempat memimpin perusahaan BUMN Industri strategi 10 tahun lamanya.",
    },
    {
      date: "1998",
      h3: "BJ Habibie Menjadi Wakil Presiden",
      h4: "14 Maret",
      p: "Mulai tahun 1998, tepatnya tanggal 14 Maret BJ Habibie diangkat menjadi Wakil Presiden ke-7 mendampingi Soeharto dalam Kabinet Pembangunan VII sampai 21 Mei 1998 saat Soeharto lengser dari jabatan presidennya.",
    },
    {
      date: "1998 - 1999",
      h3: "BJ Habibie Menjadi Presiden",
      h4: "~",
      p: "Setelah mundurnya Soeharto, BJ Habibie ditetapkan sebagai Presiden Indonesia ke-3 pada usianya yang ke 62 tahun dengan masa jabatan yang singkat, yakni 1 Mei 1998 hingga 20 Oktober 1999. ",
    },
    {
      date: "~",
      h3: "Tantangan BJ Habibie",
      h4: "~",
      p: "Bisa dikatakan ia diwarisi jabatan saat kondisi Indonesia sedang kacau dan memprihatinkan dimana banyak daerah dan wilayah yang ingin melepaskan diri dari Indonesia. Di Era Reformasi dengan yang tidak stabil dan disintegrasi setelah kerusuhan Mei 1998 di beberapa daerah di Indonesia, BJ Habibie harus mengawal semua kekacauan tersebut. BJ Habibie sigap membentuk kabinet baru dengan peran-peran penting agar mengembalikan dukungan dana moneter Internasional dan komunitas negara donor agar memulihkan ekonomi Indonesia saat itu. BJ Habibie juga membebaskan beberapa tahanan politik era Soeharto dan mengurangi kontrol untuk kebebasan berpendapat dan kegiatan organisasi. ",
    },
  ],
  [
    {
      date: "1940",
      h3: "Kelahiran Gus Dur",
      h4: "4 Agustus",
      p: "Abdurrahman Wahid atau Gus Dur dilahirkan di Jombang, Jawa Timur 4 Agustus 1940. Gus Dur merupakan putra pertama dari enam bersaudara. Ayahnya bernama KH. Wahid Hasyim yang merupakan putra dari KH. Hasyim Asy’ari, pendiri Jam’iyah Nahdlatul Ulama (NU) sebagai organisasi massa Islam terbesar di Indonesia dan sekaligus pendiri Pesantren Tebu Ireng Jombang. Ibunya bernama Hj. Sholehah merupakan putri Kh. Bisri Syansuri pendiri Pesantren Denanyar Jombang,",
    },
    {
      date: "1953",
      h3: "Lulus Sekolah Dasar",
      h4: "~",
      p: "Setelah lulus dari Sekolah Dasar (SD) pada tahun 1953, Gus Dur dikirim oleh orang tuanya untuk belajar di Yogyakarta. Untuk masuk ke Sekolah Menengah Ekonomi Pertama (SMEP) Gowongan, sekaligus menetap di Pesantren Krapyak.",
    },
    {
      date: "1956",
      h3: "Tamat dari SMP",
      h4: "~",
      p: "Tamat dari sekolah tersebut Gus Dur melanjutkan Pendidikan ke pesantren Tegalrejo, Magelang, Jawa Tengah pimpinan KH. Chaudhary. Gus Dur pun dikenal dengan ritual-ritual sufi yang mistik dengan bimbingan kiainya. Dari situlah Gus dur sering melakukan ziarah ke kuburan-kuburan para wali yang keramat di Pulau Jawa.",
    },
    {
      date: "1958",
      h3: "Gus Dur Kembali ke Jombang",
      h4: "~",
      p: "Setelah menghabiskan waktunya selama dua tahun di Pesantren Tegalrejo, Magelang, kemudian berpindah kembali ke Jombang dan menetap di pesantren Tambak Beras hingga Gus Dur berusia 20 tahun.",
    },
    {
      date: "1960",
      h3: "Gus Dur Melanjutkan Studi di Mesir",
      h4: "~",
      p: "Di Pesantren Tambak Beras, Gus Dur menjadi ustad sekaligus menjadi ketua keamanan di Pesantren milik pamannya yaitu KH. Abdul Fatah. Saat usianya 22 tahun, Gus Dur berangkat menuju Mekah untuk menunaikan ibadah haji sekaligus menuju Mesir untuk melanjutkan studi di Universitas al-Azhar.",
    },
    {
      date: "~",
      h3: "Gus Dur Menyelesaikan Pendidikan di Baghdad",
      h4: "~",
      p: "Setelah menyelesaikan pendidikan di Baghdad, Gus Dur bermaksud melanjutkan studi ke Eropa, akan tetapi persyaratannya cukup ketat karena harus menguasai Bahasa Jerman, Yunani, dan Latin. Untuk menghilangkan rasa kecewanya akhirnya Gus Dur menjadi pelajar keliling yang melakukan kunjungan ke Universitas-universitas lain. Akhirnya Gus Dur menetap di Belanda selama 6 bulan, sekaligus mendirikan suatu perkumpulan Pelajar Muslim Indonesia dan Malaysia yang tinggal di daratan Eropa.",
    },
    {
      date: "1971",
      h3: "Gus Dur Kembali ke Indonesia",
      h4: "~",
      p: "Gus Dur kembali ke Indonesia setelah terilhami sebuah berita tentang perkembangan dunia pesantren dan perjalanan studinya berakhir pada 1971. Kemudian kembali ke Jawa dan memulai kehidupan baru sekaligus menjadi perjalanan awal karirnya.",
    },
    {
      date: "1979",
      h3: "Gud Dur Ditawari Menempuh Pendidikan di Australia",
      h4: "~",
      p: "Semangat belajar Gus Dur tidak pernah surut. Tahun 1979, Gus Dur ditawari untuk menempuh pendidikan di Australia untuk mendapatkan gelar doktor, namun hal tersebut tidak bisa dipenuhi oleh Gus Dur. Gus Dur merupakan sosok yang gemar membaca dan sangat aktif memanfaatkan perpustakaan milik ayahnya dan sering berkunjung ke perpustakaan umum di Jakarta.",
    },
    {
      date: "1998",
      h3: "Gus Dur Membentuk Partai",
      h4: "Juni",
      p: "Setelah jatuhnya era Soeharto, banyak partai politik baru terbentuk. Pada Juni 1998, banyak orang dari komunitas NU berharap pada Gus Dur untuk membentuk parti politik. Pada Juli 1998, Gus Dur mulai menanggapi ide tersebut karena menyadari bahwa partai politik merupakan satu-satunya cara untuk berjuang di dunia politik (pemerintahan). Gus Dur akhirnya menyetujui pembentukan parpol yang kemudian diberi nama PKB (Partai Kebangkitan Bangsa). Beliau menjabat menjadi Ketua Dewan Penasihat.",
    },
    {
      date: "1999",
      h3: "Gus Dur Sebagai Kandidat Pemilihan Presiden",
      h4: "7 Februari",
      p: "PKB secara resmi menyatakan Gus Dur sebagai kandiat pemilihan presiden. ",
    },
    {
      date: "1999",
      h3: "PKB Beraliansi dengan PDIP",
      h4: "Juni",
      p: "Partai PKB beraliansi dengan PDIP dikarenakan tidak memiliki kursi mayoritas penuh.",
    },
    {
      date: "1999",
      h3: "Habibie Mundur dari Pemilihan Presiden",
      h4: "19 Oktober",
      p: "MPR menolak pidato pertanggungjawaban Habibie dan ia mundur dari pemilihan presiden.",
    },
    {
      date: "1999",
      h3: "Gud Dur Terpilih Sebagai Presiden",
      h4: "20 Oktober",
      p: "MPR kembali berkumpul dan mulai memilih presiden baru. Abdurrahman Wahid kemudian terpilih sebagai Presiden Indonesia ke-4 dengan 373 suara, sedangkan Megawati hanya 313 suara.",
    },
  ],
  [
    {
      date: "1879",
      h3: "Lahirnya R.A. Kartini",
      h4: "21 April",
      p: "Kartini lahir dari keturunan seorang bangsawan Jepara, Jawa Tengah. Ayahnya Raden Adipati Ario Sosroningrat yang merupakan seorang bangsawan dan ibunya merupakan keturunan orang biasa yang bernama M.A Ngasirah. Dari kerurunan bangsawan ini nama Raden Adjeng melekat pada Kartini sedari kecil.",
    },
    {
      date: "1890",
      h3: "Masa Sekolah Kartini",
      h4: "~",
      p: "Pada masa itu orang - orang pribumi belum bisa mengenyam pendidikan terutama bagi kaum wanita. Beruntung kartini memiliki kakek yang melek terhadap pendidikan barat. Ketika berumur 12 tahun Kartini disekolahkan di ELS (Europese Lagere School), dari sini kartini memperoleh banyak teman dan belajar bahasa belanda. Namun masa sekolahnya tidak berlangsung lama.",
    },
    {
      date: "1894",
      h3: "Tradisi Gadis Jawa",
      h4: "~",
      p: "Ketika kartini masih belajar dan bermain disekolahnya, Kartini terpaksa harus mengikuti adat untuk para gadis Jawa di masa itu. Sekitar usia 15 tahun para gadis harus tinggal dirumah dan tidak diperbolehkan keluar, tradisi itu disebut dengan Dipingit. Para gadis dipersiapkan untuk nantinya dijodohkan dengan seseorang ketika sudah dewasa",
    },
    {
      date: "1895",
      h3: "Mengisi Waktu dengan Surat",
      h4: "~",
      p: "Berkat sekolah di ELS dan belajar Bahasa Belanda, Kartini bisa berbahasa Belanda dan juga memiliki teman sekolah orang Belanda. Salah satunya ialah Rosa Abendanon, Kartini sering berkomunikasi dengan Rosa melalui surat. Kertini sering mengirimkan surat berbahasa belanda ke teman temannya. Tak hanya menulis surat kartini juga banyak membaca buku-buku dan juga majalah.",
    },
    {
      date: "1900",
      h3: "Munculnya Pola Pikir Wanita Modern",
      h4: "~",
      p: "Kartini banyak membaca majalah dan koran yang ada dirumahnya, tak hanya majalah dan koran Kartini juga banyak membaca buku - buku terkrnal seperti Max Havelaar dan Surat-Surat Cinta karya Multatuli dan buku berkualitas tinggi lainnya. Karitni membandingkan kehidupan wanita Belanda yang ia baca dari buku dan majalah dengan kehidupan wanita pribumi yang sangat jauh. Dari sana muncul pikiran untuk memajukan kaum wanita di pribumi.",
    },
    {
      date: "1901",
      h3: "Emansipasi Wanita",
      h4: "~",
      p: "Kartini terus menyuarakan mengenai masalah emansipasi wanita pada masa itu. Kartini berpikir bahwa hidup wanita pada saat itu jauh dari kata kebebasan dan kedilan. Melalui surat - suaratnya yang ia menyuarakan untuk kebebasan kaum wanita pribumi. Seruannya untuk memperjuangkan kebebasan tersebut banyak didukung teman-temannya yang kemudian diikuti oleh para wanita disekitar daerah tersebut.",
    },
    {
      date: "1903",
      h3: "Pernikahan Kartini",
      h4: "12 November",
      p: "Kartini dijodohkan dengan K.R.M. Adipati Ario Singgih Djojo Adhiningrat, seorang Bupati Rembang yang saat itu sudah pernah meiliki 3 orang istri. Adipati Ario sangat mendukung Kartini dalam memperjuangkan emansipasi wanita kala itu. Dari pernikahan tersebut, Kartini dikaruniai seorang anak bernama Soesalit Djojoadhiningrat yang lahir pada 13 September 1904.",
    },
    {
      date: "1904",
      h3: "Kartini Wafat",
      h4: "17 September",
      p: "Berselang 3 hari setelah kelahiran anaknya, Kartini menghembuskan nafas terakhirnya. Kartini meninggal di usia 25 tahun. Kartini dimakamkan di Desa Bulu, Kecamatan Bulu Rembang. Terdapat satu keinginan yang belum sempat terlaksanakan yakni, yakni Kartini ingin mendirikan sebuah sekolah wanita di daerah ia tinggal. Namun pada tahun 1912 Yayasan Kartini mendirkan sekolah wanita di Semarang dan kemudian diikuti dibeberapa daerah.",
    },
    {
      date: "1911",
      h3: "Buah Pikiran Kartini",
      h4: "~",
      p: "Jacques Abendanon, merupakan suami dari Rosa Abendanon sahabat Kartini. Mereka menumpulkan surat - surat yang pernah ditulis Kartini kepada teman temannya dan kemudian membukukannya dengan judul Door Duisternis tot Licht yang memiliki makna 'Dari Kegelapan Menuju Cahaya' dari Bahasa Belanda",
    },
    {
      date: "1922",
      h3: "Buku Buku Tentang Kartini",
      h4: "~",
      p: "Balai Pustaka menerbitkan buku Door Duisternis tot Licht kedalam bahasa melayu dengan judul Habis Gelap Terbitlah Terang: Boeah Pikiran yang diterjemahkan oleh Empat Saudara. Kemudian pada tahun 1938, Armijn Pane menerbitkan buku Habis Gelap Terbitlah Terang versinya sendiri. Kemudian ada buku berjudul Letters from Kartini, An Indonesian Feminist 1900–1904 dari Joost Coté yang berisi surat - surat dari buku Door Duisternis tot Licht dan beberapa surat lain yang tidak tercantum disana.",
    },
    {
      date: "1964",
      h3: "Peninggalan Kartini",
      h4: "2 Mei",
      p: "Presiden Sukarno menetapkan Kartini sebagai Pahlawan Kemerdekaan Nasional berbarengan dengan ditetapkannya 21 April sebagai Hari Kartini. W.R. Supratman juga membuat lagu yang terinspirasi dari perjuangan Kartini dengan judul Ibu Kita Kartini. Tak hanya itu ada beberapa nama jalan di Belanda menggunakan nama Kartini. Terdapat juga buku - buku dan film bertemakan Kartini yang bisa dijumpai hingga sekarang.",
    },
  ],
  [
    {
      date: "1921",
      h3: "Awal mula Frans Kaiseipo",
      h4: "~",
      p: "10 Oktober 1921 lahir sesosok penggerak di daerah Papua, orang tersebut bernama Frans Kaiseipo. Frans mengenyam pendidikan di sekolah guru agama Krinsten di Manokwari dan pernah belajar di Sekolah kursus Pegawai Papua(Papua Bestuur School). Dari sini beliau mulai perjuangannya dalam membela tanah airnya yaitu Papua.",
    },
    {
      date: "1945",
      h3: "Penggerak Nasionalisme di Papua",
      h4: "~",
      p: "Bersama Sugoro Atmoprasodjo di Sekolah Kursus Pegawai, Frans merencanakan penggabungan Nederlands Nieuw Guinea(Wilayah Papua) ke Republik Indonesia. Pada 31 Agustus Frans mengibarkan Bendera Merah Putih di Papua sebagai bentuk menegakkan eksistensi Papua bagian dari Indonesia.",
    },
    {
      date: "1946",
      h3: "Pencetus Nama Irian",
      h4: "Juli",
      p: "Frans menjadi satu satunya perwakilan orang asli Papua di Konferensi Malio. Konferensi tersebut digelar di Malio, Sulawesi Selatan yang membahas mengenai rencana pembentukan negara-negara bagian di Indonesia. Pada konferensi itu Frans mengusulkan nama Irian yang berarti 'cahaya yang mengusir kegelapan' dari bahasa Biak. Frans juga menolak rencana pembentukan Negara Indonesia Timur. Pada bulan yang sama, Frans mendirikan Partai Indonesia Merdeka di Biak.",
    },
    {
      date: "1947",
      h3: "Pemberontakan di Biak",
      h4: "",
      p: "Pada Agustus 1947, Silas Papare memimpin pergerakan untuk memperingati kemerdekaan Indonesia. Tidakan itu membuat Belanda menahan orang yang terlibat selama lebih dari tiga bulan. Selama tiga bulan tersebut Frans mengambil alih peran Papare dan terlibat aktif pada pemberontakan di Biak tahun 1948. Pada tahun 1949 Frans menolak ketika ditunjuk sebagai pemimpin deligasi Papua oleh Belanda dalam Konferensi Meja Bundar, karena ia merasa Belanda mencoba untuk mendikte dia. Akibat dari semua perlawanannya, pada tahun 1954 Frans dipenjarakan hingga tahun 1961",
    },
    {
      date: "1961",
      h3: "Operasi Trikora",
      h4: "19 Desember",
      p: "Tri Komando Rakyat (Trikora) didirikan oleh Soekarno dalam rangka untuk membatalkan pembentukan ‘negara Papua’ oleh Belanda dan menyatukan wilayah Indonesia. Melalui jalur diplomasi hingga konflik bersenjata dilakukan Indonesia dalam rangka merebut wilayah Irian Barat dari tangan Belanda. Akibatnya terbitlah Perjanjian New York, yang berisi Belanda harus menyerahkan Irian Barat ke Indonesia. Indonesia harus mengembangkan wilayah tersebut dengan kurun waktu 3 tahun dari 1963 hingga 1969. Setelah itu rakyat Irian berhak memutuskan sendiri akan ikut Indonesia atau berdiri sendiri.",
    },
    {
      date: "1964",
      h3: "Gubernur Irian",
      h4: "~",
      p: "Setelah dipenjara, Frans mendirikan sebuah partai bernama Partai Irian untuk menyatukan Irian dengan Indonesia. Kemudian ditahun 1964, Frans Kaisiepo menjadi Gubernur Irian setelah gubernur sebelumnya mengundurkan diri.  Sebagai Gubernur, Frans berupaya keras untuk mempertahankan Irian sebagai bagian dari Indonesia. Frans menggunakan Penentuan Pendapat Rakyat untuk tetap Bersatu dengan Indonesia meskipun mendapat banyak ditentang oleh rakyat asli Papua. Akhirnya pada tahun 1969, Irian diterima di Indonesai sebagai Provinsi Irian Jaya.",
    },
    {
      date: "1973",
      h3: "Karir Politik setelah Menjadi Gubernur Irian",
      h4: "~",
      p: "Setelah diangkat menjadi Gubernur Irian, Frans terpilih menjadi anggota parlemen untuk Papua dalam pemilihan MPR tahu 1973 dan diangkat menjadi Dewan Pertimbangan Agung sebagai wakil untuk urusan Papua pada tahun 1977.",
    },
    {
      date: "1979",
      h3: "Perjalanan Frans Kaisiepo",
      h4: "10 April",
      p: "Frans Kaisiepo meninggal pada 10 April 1979 dan dimakamkan di Taman Makam Pahlawan Cendrawasih yang sekarang menjadi TMP Indonesia Frans Kaiseipo di Kampung Mokmer, Kabupaten Biak Numfor. Frans meninggalkan istrinya Maria Magdalena Moorwahyuni dan seorang anak",
    },
    {
      date: "1993",
      h3: "Gelar dan Penghargaan ",
      h4: "~",
      p: "Bersamaan dengan 30 tahun penyerahan Papua ke Indonesia, Pemerintah mengangkat Frans Kaisiepo sebagai Pahlawan Nasional Indonesia. Berkat jasanya dalam mempertahankan wilayah Irian, Frans juga mendapat penghargaan Bintang Mahaputra Adipradana. Nama Frans Kaisiepo juga diabadikan menjadi nama bandara yang ada di Biak, Bandara Udara Internasional Frans Kaisiepo. Tak sampai disitu Frans Kaisiepo juga terpilih menjadi tokoh yang ada pada uang pecahan 10.000 rupiah edisi 2016.",
    },
  ],
  [
    {
      date: "1921",
      h3: "Jendral Hoegeng Lahir",
      h4: "14 Oktober",
      p: "Hoegeng Imam Santoso atau yang dikenal dengan Jendral Hoegeng lahir di Pekalongan. Lahir dari pasangan Soekarjo Kario Hatmodjo yang merupakan seorang Jaksa di Pekalongan dan Oemi Kalsoem serta memiliki dua adik perempuan. Nama Hoegeng berasal dari kata 'Bugel' yang berarti gemuk, karena tubuhnya yang gemuk semasa kecil. Sejak kecil Hoegeng sudah berkeinginan menjadi seorang Polisi.",
    },
    {
      date: "1928",
      h3: "Riwayat Pendidikan Hoegeng",
      h4: "~",
      p: "Hoegeng bersekolah di HIS (sekolah dasar) di Pekalongan dan lulus pada tahun 1934. Kemudian melanjutkan sekolahnya 3 tahun di Meer Uitgebreid Lager Onderwijs(SMP) di Pekalongan pada masa itu. Hoegeng melanjutkan pendidikan SMAnya di Yogyakarta tepatnya di Algemene Middelbare School. Kemudian melanjutkannya di Rechtshoogeschool te Batavia (perguruan tinggi hukum di Batavia), disini Hoegeng mengikuti organisasi kemahasiswaan bernama Unitas Studiosorum Indonesiensis (USI).",
    },
    {
      date: "1942",
      h3: "Awal Karir Mejadi Polisi",
      h4: "Maret",
      p: "Pada bulan ini Jelang berhasil menduduki Batavia dan menutup RHS akibatnya Hoegeng terpaksa pulang ke Pekalongan. Setelah putus dari RHS, Hoegeng mengisi waktu dengan berjualan telur dan buku sekolah bahasa Jepang. Kemudian ia ditawari kerabatnya untuk bekerja di stasiun radio Hoso Kyoku di Semarang. Sembari bekerja, Hoegeng mencoba mendaftar ke kursus polisi di Pekalongan dan berhasil masuk untuk mengikuti kurusus",
    },
    {
      date: "1943",
      h3: "Perjalanan Hoegeng Mengikuti Kursus Menjadi Polisi",
      h4: "~",
      p: "Hoegeng merasa kecewa dengan kursusnya saat ini karena kelak setelah lulus bukan menjadi perwira namun pangkat yang lebih rendah. Namun Hoegeng masih menjalaninya dengan serius dan bersungguh sungguh. Selesai dari kurusus di Pekalongan, oleh pelatihnya Hoegeng didafatarkan ke kursus perwira polisi di Sukabumi (kursus Koto Kaisatsu Gakko). Disini Hoegeng dan teman temanya merasa ditipu karena lulusan kursus ini menjadi polisi dengan pangkat yang lebih rendah dari yang dijanjikan",
    },
    {
      date: "1945",
      h3: "Menjadi Perwira Militer Angkatan Laut",
      h4: "~",
      p: "Hoegeng mendapat tawaran dari M. Nazir untuk bergabung ke angkatan laut. Hoegeng menerima tawaran tersebut dan menjadi sorang militer berpangkat mayor. Tugas pertamanya adalah merumuskan landasan dasar kepolisian militer yang pada mulanya bernama satuan Penyelidik Militer Laut Chusus (PMLC). Selama bekerja di angkatan laut, Hoegeng tinggal di Yogyakarta. Di Yogyakarta, Hoegeng juga sempat bermain peran sandiwara di radio dan dari sana Hoegeng mendapat kan seorang istri bernama Merry.",
    },
    {
      date: "1947",
      h3: "Kembalinya Belanda ke Indonesia",
      h4: "21 April",
      p: "Hoegeng yang telah berhenti dari angkatan laut kembali ke kepolisian. Pada tahun 1947 terjadi operasi militer dari Belanda mengakibatkan Hoegeng dan keluarga harus mengungsi. Hoegeng diminta untuk membantu kepolisian dengan tugas mengumpulkan materi intelijen. Namun Hoegeng ditangkap oleh NICA dan dibebaskan tiga minggu kemudian. Setelah kejadian itu Hoegeng pergi ke Jakarta dan diminta untuk menjadi asisten Wakil Kepala Djawatan Kepolisian Negara",
    },
    {
      date: "1952",
      h3: "Karir Hoegeng Sebelum Menjadi Kepala Kepolisian RI",
      h4: "~",
      p: "Hoegeng pernah menjadi Kepala Dinas Pengawasan Keamanan Negara (DPKN) di Surabaya. Ia juga pernah menjadi kepala Bareskrtim di Medan pada 1956. Hoegeng juga pernah menjadi Kepala Djawatan Imigrasi pada tahun 1960, menjadi Menteri Iuran Negara pada tahun 1965, dan menjadi Menteri Sekretaris Kabinet Inti pada tahun 1966. Setelah tahun 1966 ia memutuskan istirahat dan juga sempat bermain musik yang tampil di TVRI",
    },
    {
      date: "1968",
      h3: "Diangkat Menjadi Kepala Kepolisian RI",
      h4: "5 Mei",
      p: "Hoegeng diangkat menjadi Kapolri menggantikan Soetjipto Joedodihardjo. Selama masa jabatannya Hoegeng melakukan beberapa pembenahan dan membuat struktur kapolri menjadi lebih dinamis dan komunikatif. Hoegeng mengakhiri jabatannya pada 2 Oktober 1971 masa jabatan yang bisa dibilang cukup singkat.",
    },
    {
      date: "1975",
      h3: "Kehidupan Hoegeng diluar Kepolisian",
      h4: "~",
      p: "Diluar dunia kepolisian, Hoegeng dikenal sebagai seorang yang pandai bermain musik. Ia menjadi anggota dari kelmpok pemusik Hawaii, The Hawaiian Seniors, disana Hoegeng bernyayi dan memainkan ukulele. Hoegeng juga gemar berkebun. Selain itu ia juga sering melukis potret manusia dan pemandangan juga melukis bunga, lukisannya bergaya naturalis.",
    },
    {
      date: "2004",
      h3: "Mengenang Jendral Hoegeng",
      h4: "14 Juli",
      p: "Selama masa jabatannya didunia kepolisian Hoegeng terkenal akan kesederhanaannya. Hoegeng tidak menggunakan hasil gajinya untuk membeli barang mewah dan membelanjakan keluarganya. Hoegeng juga terkenal akan kejujurannya dalam bekerja dikala masa itu banyak pejabat yang melakukan korupsi. Bahkan pada masa Presiden Abdurrahman Wahid, beliau sangat memuji kejujuran Hoegeng dengan kalimatnya yang cukup terkenal yaitu 'hanya ada 3 polisi jujur di negara ini: polisi tidur, patung polisi, dan Hoegeng'. Hoegeng tutup usia pada usianya yang ke 82 dan dimakamkan di Taman Pemakaman Bukan Umum (TPBU) Giri Tama, Kemang, Kabupaten Bogor",
    },
  ],
];
